# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# OSSRH credentials (Maven Central)
centralUsername=a5N3Jt
centralPassword=WtnDRYS5wXBub1CaPdLXt5eZuvylbqmAe

ossrhUsername=a5N3Jt        # token username from Sonatype
ossrhPassword=WtnDRYS5wXBub1CaPdLXt5eZuvylbqmAe  # token password

signing.password=   # leave blank if no GPG passphrase

# GitHub Packages credentials (for publishing to GitHub Packages)
gpr.user=your_github_username
gpr.key=your_github_token

# GPG signing
signing.keyId=200E4F35
signing.password=
signing.secretKeyRingFile=/Users/mustafailahi/.gnupg/secring.gpg
